// <auto-generated />
using Basra.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Basra.Server.Migrations.Game
{
    [DbContext(typeof(GameContext))]
    [Migration("20210112074915_userData2")]
    partial class userData2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Basra.Server.Data.User", b =>
                {
                    b.Property<string>("IdentityUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Disconncted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("PlayedGames")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("IdentityUserId");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
