// <auto-generated />
using System;
using Basra.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Basra.Server.Migrations
{
    [DbContext(typeof(MasterContext))]
    [Migration("20210520075055_add owned items lists")]
    partial class addowneditemslists
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Basra.Server.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<string>("Fbid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMoneyAidClaimable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastMoneyAimRequestTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnedBackgroundIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnedCardBackIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnedTitleIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayedGames")
                        .HasColumnType("int");

                    b.Property<int>("RequestedMoneyAidToday")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "0",
                            Draws = 0,
                            Fbid = "0",
                            IsMoneyAidClaimable = false,
                            Level = 0,
                            Money = 0,
                            Name = "hany",
                            OwnedBackgroundIds = "[1,3]",
                            OwnedTitleIds = "[2,4]",
                            PlayedGames = 3,
                            RequestedMoneyAidToday = 0,
                            Wins = 4,
                            XP = 0
                        },
                        new
                        {
                            Id = "1",
                            Draws = 0,
                            Fbid = "1",
                            IsMoneyAidClaimable = false,
                            Level = 0,
                            Money = 0,
                            Name = "samy",
                            OwnedBackgroundIds = "[0,9]",
                            OwnedTitleIds = "[11,6]",
                            PlayedGames = 7,
                            RequestedMoneyAidToday = 0,
                            Wins = 11,
                            XP = 0
                        },
                        new
                        {
                            Id = "2",
                            Draws = 0,
                            Fbid = "2",
                            IsMoneyAidClaimable = false,
                            Level = 0,
                            Money = 0,
                            Name = "anni",
                            OwnedBackgroundIds = "[10,8]",
                            OwnedCardBackIds = "[4,9]",
                            OwnedTitleIds = "[1,3]",
                            PlayedGames = 9,
                            RequestedMoneyAidToday = 0,
                            Wins = 1,
                            XP = 0
                        },
                        new
                        {
                            Id = "3",
                            Draws = 0,
                            Fbid = "3",
                            IsMoneyAidClaimable = false,
                            Level = 0,
                            Money = 0,
                            Name = "ali",
                            PlayedGames = 2,
                            RequestedMoneyAidToday = 0,
                            Wins = 0,
                            XP = 0
                        });
                });

            modelBuilder.Entity("Basra.Server.UserRelation", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OtherUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RelationType")
                        .HasColumnType("int");

                    b.HasKey("UserId", "OtherUserId");

                    b.HasIndex("OtherUserId");

                    b.ToTable("UserRelation");
                });

            modelBuilder.Entity("Basra.Server.UserRelation", b =>
                {
                    b.HasOne("Basra.Server.User", "OtherUser")
                        .WithMany()
                        .HasForeignKey("OtherUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Basra.Server.User", "User")
                        .WithMany("Relations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OtherUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Basra.Server.User", b =>
                {
                    b.Navigation("Relations");
                });
#pragma warning restore 612, 618
        }
    }
}
