// <auto-generated />
using Basra.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Basra.Server.Migrations
{
    [DbContext(typeof(MasterContext))]
    partial class MasterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Basra.Server.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Fbid")
                        .HasColumnType("longtext");

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("PlayedGames")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "0",
                            Draws = 0,
                            Fbid = "0",
                            Money = 0,
                            Name = "hany",
                            PlayedGames = 3,
                            Wins = 4
                        },
                        new
                        {
                            Id = "1",
                            Draws = 0,
                            Fbid = "1",
                            Money = 0,
                            Name = "samy",
                            PlayedGames = 7,
                            Wins = 11
                        },
                        new
                        {
                            Id = "2",
                            Draws = 0,
                            Fbid = "2",
                            Money = 0,
                            Name = "anni",
                            PlayedGames = 9,
                            Wins = 1
                        },
                        new
                        {
                            Id = "3",
                            Draws = 0,
                            Fbid = "3",
                            Money = 0,
                            Name = "ali",
                            PlayedGames = 2,
                            Wins = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
